#' Clean Up OCR Errors
#'
#' @description Constructs a GPT prompt to correct errors in text generated by Optical Character Recognition.
#'
#' @param text The OCR text to be cleaned up
#' @param instructions Instructions to be included at the top of the GPT prompt. Defaults to "Correct the OCR errors."
#' @param model Which model variant of GPT to use. Defaults to 'gpt-3.5-turbo'
#' @param openai_api_key Your API key. By default, looks for a system environment variable called "OPENAI_API_KEY" (recommended option). Otherwise, it will prompt you to enter the API key as an argument.
#' @param max_tokens The maximum length of the model's response. Defaults to 2000
#' @param temperature The randomness of the model's response. Defaults to 0.
#'
#' @return The cleaned up text as a character object.
#' @export
#'
#' @examples
#' clean_ocr(text = "John wenf to the snore. Rosie ran ercands at the mal.")
clean_ocr <- function(text,
                      instructions = 'Correct the OCR errors.',
                      model = 'gpt-3.5-turbo',
                      max_tokens = as.integer(2000),
                      temperature = as.integer(0),
                      openai_api_key = Sys.getenv('OPENAI_API_KEY')) {

  openai <- reticulate::import("openai")

  if(openai_api_key == ''){
    stop("No API key detected in system environment. You can enter it manually using the 'openai_api_key' argument.")
  } else{
    openai$api_key = openai_api_key
  }

  # query the API
  response <- openai$ChatCompletion$create(
    model = model,
    messages = list(
      list("role" = "system", "content" = instructions),
      list("role" = "user", "content" = text)
    ),
    max_tokens = max_tokens,  # adjust as per requirements
    temperature = temperature  # adjust as per requirements
  )

  return(response$choices[[1]]$message$content)

}
