#' Clean Up OCR Errors
#'
#' @description Constructs a GPT-3 prompt to correct errors in text generated by Optical Character Recognition.
#'
#' @param text The OCR text to be cleaned up
#' @param instructions Instructions to be included at the top of the GPT-3 prompt. Defaults to "Correct the OCR errors."
#' @param model Which model variant of GPT-3 to use. Defaults to "gpt-3.5-turbo"
#' @param openai_api_key Your API key. By default, looks for a system environment variable called "OPENAI_API_KEY" (recommended option). Otherwise, it will prompt you to enter the API key as an argument.
#'
#' @return The cleaned up text as a character object.
#' @export
#'
#' @examples
#' clean_ocr(text = "John wenf to the slore. Rosie ran ercands at the mal.")
clean_ocr <- function(text,
                      instructions = 'Correct the OCR errors.',
                      model = 'gpt-3.5-turbo',
                      openai_api_key = Sys.getenv('OPENAI_API_KEY')){

  openai <- reticulate::import("openai")

  if(openai_api_key == ''){
    stop("No API key detected in system environment. You can enter it manually using the 'openai_api_key' argument.")
  } else{
    openai$api_key = openai_api_key
  }

  prompt <- paste0(instructions, "\n---\n", text, "\n---\n")

  # query the API
  if(model %in% c('gpt-3.5-turbo', 'gpt-3.5-turbo-16k')){
    # for Chat Endpoint, embed the prompt in a "messages" dictionary object
    messages <- reticulate::dict(role = 'user',
                                 content = prompt)

    # query the API
    response <- openai$ChatCompletion$create(model = model,
                                             messages = c(messages),
                                             temperature = as.integer(0),
                                             max_tokens = as.integer(2000))

    return(response$choices[[1]]$message$content)

  } else{
    response <- openai$Completion$create(
      engine = model,
      prompt = prompt,
      temperature = as.integer(0),
      max_tokens = as.integer(2000)
    )

    return(response$choices[[1]]$text)

  }

}
