#' Clean Up OCR Errors
#'
#' @description Constructs a GPT-3 prompt to errors in text generated by Optical Character Recognition.
#'
#' @param text The OCR text to be cleaned up
#' @param instructions Instructions to be included at the top of the GPT-3 prompt. Defaults to "Correct the OCR errors."
#' @param model Which model variant of GPT-3 to use. Defaults to "text-davinci-003"
#' @param openai_api_key Your API key. By default, looks for a system environment variable called "OPENAI_API_KEY" (recommended option). Otherwise, it will prompt you to enter the API key as an argument.
#'
#' @return The cleaned up text as a character object.
#' @export
#'
#' @examples
#' clean_ocr(text = "John wenf to the snore. Rosie ran ercands at the mal.")
clean_ocr <- function(text,
                      instructions = 'Correct the OCR errors.',
                      model = 'text-davinci-003',
                      openai_api_key = Sys.getenv('OPENAI_API_KEY')){

  openai <- reticulate::import("openai")

  if(is.null(openai_api_key) | Sys.getenv('OPENAI_API_KEY') == ''){
    stop("No API key detected in system environment. You can enter it manually using the 'openai_api_key' argument.")
  } else{
    openai$api_key = openai_api_key
  }

  # query the API
  response <- openai$Completion$create(
    engine = model,
    prompt = paste0(instructions, "\n---\n", text, "\n---\n"),
    temperature = as.integer(0),
    max_tokens = as.integer(2000)
  )

  return(response$choices[[1]]$text)

}
